/**
 * Copyright Schrodinger, LLC
 * All rights reserved.
 *
 * @providesModule ActionTypes
 */

'use strict';

export const COLUMN_REORDER_START = 'COLUMN_REORDER_START';
export const COLUMN_REORDER_END = 'COLUMN_REORDER_END';
export const COLUMN_REORDER_MOVE = 'COLUMN_REORDER_MOVE';
export const ROW_REORDER_START = 'ROW_REORDER_START';
export const ROW_REORDER_MOVE = 'ROW_REORDER_MOVE';
export const ROW_REORDER_END = 'ROW_REORDER_END';
export const CELL_EDIT_END = 'CELL_EDIT_END';
export const CELL_EDIT_START = 'CELL_EDIT_START';
export const COLUMN_RESIZE = 'COLUMN_RESIZE';
export const INITIALIZE = 'INITIALIZE';
export const PROP_CHANGE = 'PROP_CHANGE';
export const SCROLL_START = 'SCROLL_START';
export const SCROLL_END = 'SCROLL_END';
export const SCROLL_TO_X = 'SCROLL_TO_X';
export const SCROLL_TO_Y = 'SCROLL_TO_Y';
export const DEAL_ROW_RENAME_MODAL = 'DEAL_ROW_RENAME_MODAL'
export const DEAL_ROW_DELETE_MODAL = 'DEAL_ROW_DELETE_MODAL'
export const DEAL_ROW_MOVE_MODAL = 'DEAL_ROW_MOVE_MODAL'
export const DEAL_SECTION_RENAME_MODAL = 'DEAL_SECTION_RENAME_MODAL'
export const DEAL_SECTION_DELETE_MODAL = 'DEAL_SECTION_DELETE_MODAL'
export const DEAL_SECTION_UNDO_DELETE_MESSAGE = 'DEAL_SECTION_UNDO_DELETE_MESSAGE'
export const DEAL_SECTION_COLOR_MENU = 'DEAL_SECTION_COLOR_MENU'
export const DEAL_ROW_HEADER_DRAWER = 'DEAL_ROW_HEADER_DRAWER'
export const HEIGHT_INCREASE = 'HEIGHT_INCREASE';
