/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_appsync_graphqlEndpoint": "https://fjuypof5xrctpbmtjfm4zx5c6a.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5fuapofitfalfgo4f4a3pocz5q",
    "aws_cognito_identity_pool_id": "ap-northeast-2:f1455023-9123-4838-a23f-24a32199b85f",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_ijdyPKx2y",
    "aws_user_pools_web_client_id": "45990m60nt54a49oqa5q6sl9di",
    "oauth": {}
};


export default awsmobile;
